# Description:
#   Pick a name you like, normally the name of the repository.
# Example:
namespace: OWASP

# Description:
#   Working directory, normally used as the path to the repository.
# Example:
working_dir: .

# Description:
#   SAST for source code.
# Example:
path:
  # Description:
  #   Target files used in the analysis.
  # Example:
  include:
    # Absolute path
    - .
    # Relative path to `working_dir`
    - .
