name: Makes CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        
      - name: do stuff
        run: |
          docker build . --file Dockerfile -t testing
          docker run testing m gitlab:fluidattacks/universe@trunk /skims scan stuff/config.yml
